<script type="text/javascript">
<!--

document.write( '<div class=\"line\"></div>\n' );
document.write( '<div class=\"wrapper\">\n' );
document.write( '  <header role=\"banner\">\n' );
document.write( '    <nav role=\"navigation\">\n' );
document.write( '      <h1><a href=\"#\">Parihar Cloth Store</a></h1>\n' );
document.write( '      <ul class=\"nav-ul\">\n' );
document.write( '        <li><a href=\"#\">Home</a></li>\n' );
document.write( '        <li><a href=\"#\">About Us</a></li>\n' );
document.write( '        <li><a href=\"#\">know more</a></li>\n' );
document.write( '        <li><a href=\"#\">Services</a></li>\n' );
document.write( '        <li><a href=\"#\">Contacts</a></li>\n' );
document.write( '      </ul>\n' );
document.write( '    </nav>\n' );
document.write( '  </header>\n' );
document.write( '  <main role=\"main\">\n' );
document.write( '    <section class=\"sec-intro\" role=\"section\">\n' );
document.write( '      <img src=\"https://www.techweekeurope.co.uk/wp-content/uploads/2012/07/wifimountaindownload.jpg\" alt=\"\" />\n' );
document.write( '      <h1>Be fashnable!</h1>\n' );
document.write( '    </section>\n' );
document.write( '    <section class=\"sec-boxes\" role=\"section\">\n' );
document.write( '      <adrticle class=\"box\">\n' );
document.write( '        <h1>Good quality</h1>\n' );
document.write( '        <p>very good quality material.</p>\n' );
document.write( '        <button class=\"button\" type=\"button\" role=\"button\" value=\"MORE\">More</button>\n' );
document.write( '      </adrticle>\n' );
document.write( '      <adrticle class=\"box\">\n' );
document.write( '        <h1>Creative</h1>\n' );
document.write( '        <p>creative design.</p>\n' );
document.write( '        <button class=\"button\" type=\"button\" role=\"button\" value=\"MORE\">More</button>\n' );
document.write( '      </adrticle>\n' );
document.write( '      <adrticle class=\"box\">\n' );
document.write( '        <h1>Bold</h1>\n' );
document.write( '        <p>Bold styles of dress.</p>\n' );
document.write( '        <button class=\"button\" type=\"button\" role=\"button\" value=\"MORE\">More</button>\n' );
document.write( '      </adrticle>\n' );
document.write( '      <adrticle class=\"box\">\n' );
document.write( '        <h1>Smart</h1>\n' );
document.write( '        <p>smart people prefer us.</p>\n' );
document.write( '        <button class=\"button\" type=\"button\" role=\"button\" value=\"MORE\">More</button>\n' );
document.write( '      </adrticle>\n' );
document.write( '    </section>\n' );
document.write( '    <section class=\"sec-events\" role=\"section\">\n' );
document.write( '      <hr />\n' );
document.write( '      <h1>Our Branches</h1>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Parihar Cloth Store</h1>\n' );
document.write( '        <p>20/499 CHB Jodhpur</p>\n' );
document.write( '        <a class=\"link\" href=\"#\">more...</a>\n' );
document.write( '      </article>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Gomti Dresses</h1>\n' );
document.write( '        <p>20/499 CHB Jodhpur</p>\n' );
document.write( '        <a class=\"link\" href=\"#\">more...</a>\n' );
document.write( '      </article>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Parihar Cloth Store</h1>\n' );
document.write( '        <p>Pratap Nagar Jodhpur </p>\n' );
document.write( '        <a class=\"link\" href=\"#\">more...</a>\n' );
document.write( '      </article>\n' );
document.write( '      <article>\n' );
document.write( '       
document.write( '  <nav role=\"navigation\">\n' );
document.write( '    <ul class=\"nav-ul\">\n' );
document.write( '      <li><a href=\"#\">Home</a></li>\n' );
document.write( '      <li><a href=\"#\">About Us</a></li>\n' );
document.write( '      <li><a href=\"#\">Technologies</a></li>\n' );
document.write( '      <li><a href=\"#\">Projects</a></li>\n' );
document.write( '      <li><a href=\"#\">Contacts</a></li>\n' );
document.write( '    </ul>\n' );
document.write( '</footer>\n' );
document.write( '<div class=\"line\"></div>' );

//-->
</script>

