document.write( '\n' );
document.write( '<div class=\"line\"></div>\n' );
document.write( '<div class=\"wrapper\">\n' );
document.write( '  <header role=\"banner\">\n' );
document.write( '    <nav role=\"navigation\">\n' );
document.write( '      <h1><a href=\"#\">Parihar Cloth Store</a></h1>\n' );
document.write( '      <ul class=\"nav-ul\">\n' );
document.write( '        <li><a href=\"#\">Home</a></li>\n' );
document.write( '        <li><a href=\"#\">About Us</a></li>\n' );
document.write( '        <li><a href=\"#\">know more</a></li>\n' );
document.write( '        <li><a href=\"#\">Services</a></li>\n' );
document.write( '        <li><a href=\"#\">Contacts</a></li>\n' );
document.write( '      </ul>\n' );
document.write( '    </nav>\n' );
document.write( '  </header>\n' );
document.write( '  <main role=\"main\">\n' );
document.write( '    <section class=\"sec-intro\" role=\"section\">\n' );
document.write( '      <img src=\"https://www.techweekeurope.co.uk/wp-content/uploads/2012/07/wifimountaindownload.jpg\" alt=\"\" />\n' );
document.write( '      <h1>Be fashnable!</h1>\n' );
document.write( '    </section>\n' );
document.write( '    <section class=\"sec-boxes\" role=\"section\">\n' );
document.write( '      <adrticle class=\"box\">\n' );
document.write( '        <h1>Good quality</h1>\n' );
document.write( '        <p>very good quality material.</p>\n' );
document.write( '        <button class=\"button\" type=\"button\" role=\"button\" value=\"MORE\">More</button>\n' );
document.write( '      </adrticle>\n' );
document.write( '      <adrticle class=\"box\">\n' );
document.write( '        <h1>Creative</h1>\n' );
document.write( '        <p>creative design.</p>\n' );
document.write( '        <button class=\"button\" type=\"button\" role=\"button\" value=\"MORE\">More</button>\n' );
document.write( '      </adrticle>\n' );
document.write( '      <adrticle class=\"box\">\n' );
document.write( '        <h1>Bold</h1>\n' );
document.write( '        <p>Bold styles of dress.</p>\n' );
document.write( '        <button class=\"button\" type=\"button\" role=\"button\" value=\"MORE\">More</button>\n' );
document.write( '      </adrticle>\n' );
document.write( '      <adrticle class=\"box\">\n' );
document.write( '        <h1>Smart</h1>\n' );
document.write( '        <p>smart people prefer us.</p>\n' );
document.write( '        <button class=\"button\" type=\"button\" role=\"button\" value=\"MORE\">More</button>\n' );
document.write( '      </adrticle>\n' );
document.write( '    </section>\n' );
document.write( '    <section class=\"sec-events\" role=\"section\">\n' );
document.write( '      <hr />\n' );
document.write( '      <h1>Our Branches</h1>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Parihar Cloth Store</h1>\n' );
document.write( '        <p>20/499 CHB Jodhpur</p>\n' );
document.write( '        <a class=\"link\" href=\"#\">more...</a>\n' );
document.write( '      </article>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Gomti Dresses</h1>\n' );
document.write( '        <p>20/499 CHB Jodhpur</p>\n' );
document.write( '        <a class=\"link\" href=\"#\">more...</a>\n' );
document.write( '      </article>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Parihar Cloth Store</h1>\n' );
document.write( '        <p>Pratap Nagar Jodhpur </p>\n' );
document.write( '        <a class=\"link\" href=\"#\">more...</a>\n' );
document.write( '      </article>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Space Tech Expo</h1>\n' );
document.write( '        <p>Space Tech Expo is the West Coast\'s premier B2B space event for spacecraft, satellite, launch vehicle and space-related technologies. Taking place in Long Beach, the Space Tech Expo exhibition and conference brings together global decision-makers involved in the design, build and testing of spacecraft, satellite, launch vehicle and space-related technologies. Leading the West Coast space and satellite industry, Space Tech Expo is where end-users connect with solution providers.</p>\n' );
document.write( '        <a class=\"link\" href=\"#\">more...</a>\n' );
document.write( '      </article>\n' );
document.write( '    </section>\n' );
document.write( '    <section class=\"sec-projects\" role=\"section\">\n' );
document.write( '      <hr />\n' );
document.write( '      <h1>Previous Projects</h1>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Neural network for Google</h1>\n' );
document.write( '        <p>People from Google approached us this January with offer to create new neural network for whole Google\'s ecosystem. This idea was very interesting and looked almost impossible at first glance. However, our engineers proved their expertise and built amazing autonomous platform. <a class=\"link\" href=\"#\">more...</a></p>\n' );
document.write( '      </article>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Faster operating system for Apple</h1>\n' );
document.write( '        <p>For a years, since founding days of a company, Apple always worked with its own operating system. In October, this was about to change. Our company got chance to rewrite the history by creating brand new OS for Apple. It was very difficult and all our employees worked hard every day. <a class=\"link\" href=\"#\">more...</a></p>\n' );
document.write( '      </article>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Manufacturing technology for Intel</h1>\n' );
document.write( '        <p>Intel has been manufacturing company for many years. They always used the latest technologies to achieve the best results with lowest costs. However, this was not enough. Intel decided to offer us something that could disrupt whole technology sector. <a class=\"link\" href=\"#\">more...</a></p>\n' );
document.write( '      </article>\n' );
document.write( '    </section>\n' );
document.write( '    <section class=\"sec-standards\" role=\"section\">\n' );
document.write( '      <hr />\n' );
document.write( '      <h1>Our Standards</h1>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Excellence</h1>\n' );
document.write( '        <p>Our goal is to give our customers the best solutions in highest aquality. Our employees strive for excellence and work hard to achieve it. Everything must work and be reliable. Great design must be both, aesthetic and functional. Product or service that pass these conditions will be everlasting.</p>\n' );
document.write( '      </article>\n' );
document.write( '      <article>\n' );
document.write( '        <h1>Uniqueness</h1>\n' );
document.write( '        <p>Our mantra is to create new paths. We are not interested in copying others because we know, that if you want to succeed, you have to be different, unique. Our customers know that we create unique products and experience for them. This is the best way to differentiate us and our brand from the noise on market. Unique, different and proud.</p>\n' );
document.write( '      </article>\n' );
document.write( '    </section>\n' );
document.write( '    <section class=\"sec-partners\" role=\"section\">\n' );
document.write( '      <hr />\n' );
document.write( '      <h1>Our Partners</h1>\n' );
document.write( '      <div class=\"row\">\n' );
document.write( '        <div class=\"logo-container\">\n' );
document.write( '          <img src=\"https://i.imgur.com/oSriTuP.png\" alt=\"Google logo\" />\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"logo-container\">\n' );
document.write( '          <img src=\"https://i.imgur.com/kRgvevC.png\" alt=\"Apple logo\" />\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"logo-container\">\n' );
document.write( '          <img src=\"https://i.imgur.com/ZZjeIP3.png\" alt=\"Wii logo\" />\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"logo-container\">\n' );
document.write( '          <img src=\"https://i.imgur.com/536rtCW.png\" alt=\"Valve logo\" />\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"logo-container\">\n' );
document.write( '          <img src=\"https://i.imgur.com/VTq1c9p.png\" alt=\"Adithya Institute of Technology logo\" />\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"logo-container\">\n' );
document.write( '          <img src=\"https://i.imgur.com/GdYoyxo.png\" alt=\"Intel logo\" />\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </section>\n' );
document.write( '  </main>\n' );
document.write( '</div>\n' );
document.write( '<footer>\n' );
document.write( '  <nav role=\"navigation\">\n' );
document.write( '    <ul class=\"nav-ul\">\n' );
document.write( '      <li><a href=\"#\">Home</a></li>\n' );
document.write( '      <li><a href=\"#\">About Us</a></li>\n' );
document.write( '      <li><a href=\"#\">Technologies</a></li>\n' );
document.write( '      <li><a href=\"#\">Projects</a></li>\n' );
document.write( '      <li><a href=\"#\">Contacts</a></li>\n' );
document.write( '    </ul>\n' );
document.write( '  </nav>\n' );
document.write( '  <p class=\"copy\">© Alex Devero Design 2014</p>\n' );
document.write( '</footer>\n' );
document.write( '<div class=\"line\"></div>' );

